version: "2.1"
orbs:
  node: circleci/node@4.7.0
  codecov: codecov/codecov@1.0.2
jobs:
  test:
    executor:
      name: node/default
      tag: "13.14"
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
      - store_artifacts:
          path: coverage
  upload_coverage:
    executor:
      name: node/default
      tag: "13.14"
    steps:
      - codecov/upload:
          file: ./coverage

workflows:
  run_tests:
    jobs:
      - test
      - upload_coverage:
          requires:
            - test
